New files with MUI library
zbednarz/Task-List pull request #3
Opened 2022-09-08 12:37 UTC by zbednarz

Updated the code with MUI Library

2022-09-12 06:29 UTC, SMysakowski requested changes

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyInput.js
> +import { TextField } from "@mui/material";
```suggestion
import TextField from "@mui/material/TextField";
```

https://mui.com/material-ui/guides/minimizing-bundle-size/#development-environment

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyInput.js
> +}));
```suggestion
const MyInput = styled(TextField)(({theme})=>({
    background: theme.palette.common.white,
    borderRadius: "15px",
    fontSize: "60px",     
}));
```

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyIcons.js
> +
remove unused code

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyButton.js
> +import { Button } from "@mui/material";
import directly

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyButton.js
> +import { styled } from "@mui/system";
incorrect import

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyButton.js
> +const MyButton = styled(Button)(() => ({}));
unused

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyButton.js
> +}));
use colors and spacing from theme

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyButton.js
> +}));
as above

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyAvatar.js
> +}));
use spacing from theme

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyAvatar.js
> +
unused

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyAvatar.js
> +import { styled } from "@mui/system";
incorrect import

2022-09-12 06:29 UTC, SMysakowski commented on src/styles/MyAvatar.js
> +import { Avatar } from "@mui/material";
import directly. Last comment has explanation

2022-09-12 06:29 UTC, SMysakowski commented on src/components/TodoList.js
>    const onDeleter = (todo) => {
onDelete

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Todo.js
>        </li>
nested <li>?

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Todo.js
> +    <ThemeProvider theme={theme}>
Theme provider should be on the top of app

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Todo.js
> +import { Stack } from "@mui/system";
incorrect import

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Modal.js
> +                />
inline styles

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Modal.js
> +            <Box sx={style}>
you shouldn't use sx. It is slower than styled

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Modal.js
> +            }}
inline styles

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Modal.js
> +  const [open, setOpen] = React.useState(true);
import only useState not whole react

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Modal.js
> +import { Fade } from "@mui/material";
import directly

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Modal.js
> +    <ThemeProvider theme={theme}>
move to the top of the app

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Form.js
> +        <Box sx={{ minWidth: 150 }}>
move to styled instead sx

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Form.js
> +          // sx={{}}
remove

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Form.js
> +          }}
move to styled

2022-09-12 06:29 UTC, SMysakowski commented on src/components/Form.js
> +    <ThemeProvider theme={theme}>
move to top of the app

2022-09-12 06:29 UTC, SMysakowski commented on src/Holder.js
> +  }));
to spacing and colors use theme property

2022-09-12 06:29 UTC, SMysakowski commented on src/Holder.js
> +import { Box } from "@mui/material";
import directly

2022-09-12 06:29 UTC, SMysakowski commented on src/App.js
> +import { ThemeProvider } from "@mui/material/styles";
wrap theme provider once on the top of app

2022-09-12 06:29 UTC, SMysakowski commented on src/App.js
> +} from "@mui/material";
Import directly. In this way, you add whole components to the app bundle

2022-09-29 08:56 UTC, zbednarz commented on src/styles/MyButton.js
> +import { styled } from "@mui/system";
Button import has been corrected. Import styled I have additional questions.

2022-10-04 07:29 UTC, SMysakowski approved these changes

2022-10-04 07:29 UTC, merged